name: inventory_management_web
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it:
  shared_preferences:
  permission_handler:
  qr_flutter:
  qrscan:
  path_provider:
  charts_flutter:
  giffy_dialog:
  http:
  json_to_form:
    path: assets/jsontoform/


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/Images/logo_1.jpg
    - assets/Images/logo_2.jpg
    - assets/Images/logo_3.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: FiraSans
        fonts:
          - asset: fonts/FireSans/FiraSansCondensed-Black.ttf
            weight: 900
          - asset: fonts/FireSans/FiraSansCondensed-BlackItalic.ttf
            weight: 900
            style: italic
          - asset: fonts/FireSans/FiraSansCondensed-Bold.ttf
            weight: 700
          - asset: fonts/FireSans/FiraSansCondensed-BoldItalic.ttf
            weight: 700
            style: italic
          - asset: fonts/FireSans/FiraSansCondensed-ExtraBold.ttf
            weight: 800
          - asset: fonts/FireSans/FiraSansCondensed-ExtraBoldItalic.ttf
            weight: 800
            style: italic
          - asset: fonts/FireSans/FiraSansCondensed-ExtraLight.ttf
            weight: 200
          - asset: fonts/FireSans/FiraSansCondensed-ExtraLightItalic.ttf
            style: italic
            weight: 200
          - asset: fonts/FireSans/FiraSansCondensed-Italic.ttf
            style: italic
          - asset: fonts/FireSans/FiraSansCondensed-Light.ttf
            weight: 300
          - asset: fonts/FireSans/FiraSansCondensed-LightItalic.ttf
            style: italic
            weight: 300
          - asset: fonts/FireSans/FiraSansCondensed-Medium.ttf
            weight: 500
          - asset: fonts/FireSans/FiraSansCondensed-MediumItalic.ttf
            style: italic
            weight: 500
          - asset: fonts/FireSans/FiraSansCondensed-Regular.ttf
            weight: 400
          - asset: fonts/FireSans/FiraSansCondensed-SemiBold.ttf
            weight: 600
          - asset: fonts/FireSans/FiraSansCondensed-SemiBoldItalic.ttf
            weight: 600
            style: italic
          - asset: fonts/FireSans/FiraSansCondensed-Thin.ttf
            weight: 100
          - asset: fonts/FireSans/FiraSansCondensed-ThinItalic.ttf
            weight: 100
            style: italic
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
